# The Job to run the SQLcl container with embedded SQL
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sqlcl-runner-job-
  namespace: obaas-dev
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sqlcl-container
        image: container-registry.oracle.com/database/sqlcl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          export TNS_ADMIN=/etc/oracle/wallet
          
          # Create the SQL script inline
          cat > /tmp/run.sql << 'EOF'
          SET SERVEROUTPUT ON;
          WHENEVER SQLERROR EXIT SQL.SQLCODE;
          
          create user customer identified by Welcome-12345;
          grant db_developer_role to customer;
          grant unlimited tablespace to customer;

          create user account identified by Welcome-12345;
          grant db_developer_role to customer;
          grant unlimited tablespace to customer;
          commit;

          /
          EXIT;
          EOF
          
          # Execute the SQL script
          sql $(DB_USER)/$(DB_PASSWORD)@$(TNS_ALIAS) @/tmp/run.sql
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: m2two-db-secrets
              key: db.username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: m2two-db-secrets
              key: db.password
        - name: TNS_ALIAS
          valueFrom:
            secretKeyRef:
              name: m2two-db-secrets
              key: db.service
        volumeMounts:
        - name: db-wallet-volume
          mountPath: /etc/oracle/wallet
          readOnly: true
      volumes:
      - name: db-wallet-volume
        secret:
          secretName: obaas-adb-tns-admin-1